/**
 * index.ts — Public API for the anyql npm package.
 *
 * Usage:
 *   import { analyze } from 'anyql';
 *
 *   const result = await analyze(
 *     'SELECT id, name FROM users WHERE id = $1',
 *     { dialect: 'postgresql', host: 'localhost', port: 5432,
 *       user: 'postgres', password: 'secret', database: 'mydb' }
 *   );
 *   console.log(result.columns);    // [{ name: 'id', tsType: 'string', ... }, ...]
 *   console.log(result.parameters); // [{ index: 1, dbTypeName: 'uuid', requiresCast: true, ... }]
 */

import type {
  AnalyzeResult,
  AnalyzeErrorResult,
  ConnectionInfo,
} from "./types.js";
import * as socketModule from "./nodeSocket.js";

export type {
  AnalyzeResult,
  AnalyzeErrorResult,
  ColumnInfo,
  ParameterInfo,
  ConnectionInfo,
} from "./types.js";

// ── WASM bootstrap ──────────────────────────────────────────────────────────
// Use loose typing for the dotnet host builder since we import the runtime
// dynamically and TypeScript can't resolve it at compile time.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DotnetRuntimeModule = { dotnet: any };

interface WasmAssemblyExports {
  AnyQL: {
    Wasm: {
      WasmExports: {
        Analyze: (requestJson: string) => Promise<string>;
        InitializeSocket: (socketModuleUrl: string) => Promise<void>;
      };
    };
  };
}

// Singleton promise so that concurrent callers always share one WASM load.
// Using a bare `_analyze` flag would allow a race: multiple concurrent callers
// all pass the `if (_analyze)` check before the first load completes, then
// each calls dotnet.create() in parallel.  dotnet.js uses module-level state
// (the `ht` guard in `pt()`) that is set true by the first call; subsequent
// calls find `ht=true`, skip the initialization, and leave `qe.locateFile`
// undefined — causing a TypeError later.
let _analyzePromise:
  | Promise<(requestJson: string) => Promise<string>>
  | undefined;

async function ensureWasmLoaded(): Promise<
  (requestJson: string) => Promise<string>
> {
  if (!_analyzePromise) {
    _analyzePromise = loadWasmInternal();
  }
  return _analyzePromise;
}

async function loadWasmInternal(): Promise<
  (requestJson: string) => Promise<string>
> {
  // Resolve the WASM dist directory relative to this file
  const { fileURLToPath, pathToFileURL } = await import("node:url");
  const { dirname, join } = await import("node:path");
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const wasmDir = join(__dirname, "wasm");

  // Provide the socket module to the WASM runtime via globalThis
  // so that JSImport("connect", "anyql-socket") etc. can find it.
  (globalThis as Record<string, unknown>)["anyql-socket"] = socketModule;

  // Load the dotnet.js bootstrapper generated by dotnet build (AppBundle)
  const dotnetModule = (await import(
    `${wasmDir}/_framework/dotnet.js`
  )) as DotnetRuntimeModule;
  const { dotnet } = dotnetModule;

  const runtime = await dotnet.withDiagnosticTracing(false).create();

  const config = runtime.getConfig();
  const exports = (await runtime.getAssemblyExports(
    config.mainAssemblyName,
  )) as WasmAssemblyExports;

  // Register the socket JS module so C# [JSImport] calls can resolve it.
  // Construct the URL at runtime via pathToFileURL to prevent bundlers from
  // inlining the module content as a data URL (Rolldown/Vite 8 behaviour).
  const socketModuleUrl = pathToFileURL(join(__dirname, "nodeSocket.js")).href;
  await exports.AnyQL.Wasm.WasmExports.InitializeSocket(socketModuleUrl);

  return exports.AnyQL.Wasm.WasmExports.Analyze;
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Analyzes a SQL query against the specified database and returns
 * column metadata and parameter type information.
 *
 * @param sql   The SQL statement (SELECT, or DML with RETURNING for PostgreSQL).
 * @param conn  Database connection parameters.
 * @throws {Error} if the server returns an error or the connection fails.
 */
export async function analyze(
  sql: string,
  conn: ConnectionInfo,
): Promise<AnalyzeResult> {
  const analyzeWasm = await ensureWasmLoaded();
  const requestJson = JSON.stringify({ sql, ...conn });
  const responseJson = await analyzeWasm(requestJson);
  const response = JSON.parse(responseJson) as
    | AnalyzeResult
    | AnalyzeErrorResult;

  if ("error" in response) {
    throw new Error(response.error);
  }
  return response;
}
